version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: medusa_postgres
    environment:
      POSTGRES_USER: medusa
      POSTGRES_PASSWORD: medusa
      POSTGRES_DB: medusa
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:6
    container_name: medusa_redis
    ports:
      - "6379:6379"

  medusa:
    image: node:18-alpine
    container_name: medusa_backend
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "9000:9000"
    environment:
      DATABASE_URL: postgres://medusa:medusa@postgres:5432/medusa
      REDIS_URL: redis://redis:6379
      NODE_ENV: development
    depends_on:
      - postgres
      - redis
    command: sh -c "apk add --no-cache python3 make g++ && corepack enable && corepack prepare yarn@3.2.1 --activate && yarn install && yarn start"

volumes:
  pgdata:

